name = "testing"
main = "src/index.js"
compatibility_date = "2022-12-06"


[env.production]
name = "webfingerio-prod-new"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    {binding = "webfingerio_prod_auth", id = "EXAMPLE KV ID"},
    {binding = "webfingerio_prod_data", id = "EXAMPLE KV ID"}
]
routes = [
  "webfinger.io/",
  "webfinger.io/favicon.ico",
  "webfinger.io/robots.txt",
  "webfinger.io/.well-known/*",
  "webfinger.io/apiv1/*"
]
